return {
  ansi = require("balm/m/ansi"),
  assertions = require("balm/m/assertions"),
  color = require("balm/m/color"),
  cuboid = require("balm/m/cuboid"),
  dyn_vector = require("balm/m/dyn_vector"),
  easers = require("balm/m/easers"),
  list = require("balm/m/list"),
  number = require("balm/m/number"),
  object = require("balm/m/object"),
  pack = require("balm/m/pack"),
  path = require("balm/m/path"),
  plot = require("balm/m/plot"),
  pretty_units = require("balm/m/pretty_units"),
  rect = require("balm/m/rect"),
  string = require("balm/m/string"),
  table = require("balm/m/table"),
  vector2 = require("balm/m/vector/2"),
  vector3 = require("balm/m/vector/3"),
  vector4 = require("balm/m/vector/4"),
  value = require("balm/m/value"),
  wave = require("balm/m/wave"),
}
