require("balm/tests/s/data_matrix_test")
require("balm/tests/s/linked_list_test")
require("balm/tests/s/list_test")
require("balm/tests/s/min_heap_test")
require("balm/tests/s/records_test")
require("balm/tests/s/ring_buffer_test")
