require("balm/tests/u/bit_test")
require("balm/tests/u/dir8_test")
require("balm/tests/u/id_generator_test")
require("balm/tests/u/id128_generator_test")
require("balm/tests/u/string_buffer_test")
require("balm/tests/u/timeline_test")
require("balm/tests/u/tweener_test")
require("balm/tests/u/u128_test")
