local Luna = require("balm/luna")
local M = require("balm/m/units")

local case = Luna:new("balm.m.units")

case:describe("binary", function (t2)
  t2:test("can convert to and from all units", function (t3)
    for key, scale in pairs(M.BINARY_UNITS) do
      local v = M.from_binary(1, key)
      t3:assert_eq(scale, v)
      t3:assert_eq(M.to_binary(v, key), 1)
    end
  end)
end)

case:describe("from_binary/2", function (t2)
  t2:test("can create a base value given its converted form", function (t3)
    t3:assert_eq(2 * 2 ^ 10, M.from_binary(2, "Ki"))
    t3:assert_eq(2 * 2 ^ 20, M.from_binary(2, "Mi"))
    t3:assert_eq(2 * 2 ^ 30, M.from_binary(2, "Gi"))
    t3:assert_eq(2 * 2 ^ 40, M.from_binary(2, "Ti"))
    t3:assert_eq(2 * 2 ^ 50, M.from_binary(2, "Pi"))
    t3:assert_eq(2 * 2 ^ 60, M.from_binary(2, "Ei"))
    t3:assert_eq(2 * 2 ^ 70, M.from_binary(2, "Zi"))
    t3:assert_eq(2 * 2 ^ 80, M.from_binary(2, "Yi"))

    t3:assert_eq(2 * 2 ^ 10, M.from_binary(2, "kibi"))
    t3:assert_eq(2 * 2 ^ 20, M.from_binary(2, "mebi"))
    t3:assert_eq(2 * 2 ^ 30, M.from_binary(2, "gibi"))
    t3:assert_eq(2 * 2 ^ 40, M.from_binary(2, "tebi"))
    t3:assert_eq(2 * 2 ^ 50, M.from_binary(2, "pebi"))
    t3:assert_eq(2 * 2 ^ 60, M.from_binary(2, "exbi"))
    t3:assert_eq(2 * 2 ^ 70, M.from_binary(2, "zebi"))
    t3:assert_eq(2 * 2 ^ 80, M.from_binary(2, "yobi"))
  end)
end)

case:describe("to_binary/2", function (t2)
  t2:test("can calculate a scaled value from its base value", function (t3)
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 10, "Ki"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 20, "Mi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 30, "Gi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 40, "Ti"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 50, "Pi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 60, "Ei"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 70, "Zi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 80, "Yi"))

    t3:assert_eq(2, M.to_binary(2 * 2 ^ 10, "kibi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 20, "mebi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 30, "gibi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 40, "tebi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 50, "pebi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 60, "exbi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 70, "zebi"))
    t3:assert_eq(2, M.to_binary(2 * 2 ^ 80, "yobi"))
  end)
end)

case:describe("from_metric/2", function (t2)
  t2:test("can create a base value given its converted form", function (t3)
    t3:assert_eq(2e-1, M.from_metric(2, "d"))
    t3:assert_eq(2e-2, M.from_metric(2, "c"))
    t3:assert_eq(2e-3, M.from_metric(2, "m"))
    t3:assert_eq(2e-6, M.from_metric(2, "μ"))
    t3:assert_eq(2e-9, M.from_metric(2, "n"))
    t3:assert_eq(2e-12, M.from_metric(2, "p"))
    t3:assert_eq(2e-15, M.from_metric(2, "f"))
    t3:assert_eq(2e-18, M.from_metric(2, "a"))
    t3:assert_eq(2e-21, M.from_metric(2, "z"))
    t3:assert_eq(2e-24, M.from_metric(2, "y"))

    t3:assert_eq(2e+1, M.from_metric(2, "da"))
    t3:assert_eq(2e+2, M.from_metric(2, "h"))
    t3:assert_eq(2e+3, M.from_metric(2, "k"))
    t3:assert_eq(2e+6, M.from_metric(2, "M"))
    t3:assert_eq(2e+9, M.from_metric(2, "G"))
    t3:assert_eq(2e+12, M.from_metric(2, "T"))
    t3:assert_eq(2e+15, M.from_metric(2, "P"))
    t3:assert_eq(2e+18, M.from_metric(2, "E"))
    t3:assert_eq(2e+21, M.from_metric(2, "Z"))
    t3:assert_eq(2e+24, M.from_metric(2, "Y"))
  end)
end)

case:describe("to_metric/2", function (t2)
  t2:test("can calculate a scaled value from its base value", function (t3)
    t3:assert_eq(2, M.to_metric(2e-1, "d"))
    t3:assert_eq(2, M.to_metric(2e-2, "c"))
    t3:assert_eq(2, M.to_metric(2e-3, "m"))
    t3:assert_eq(2, M.to_metric(2e-6, "μ"))
    t3:assert_eq(2, M.to_metric(2e-9, "n"))
    t3:assert_eq(2, M.to_metric(2e-12, "p"))
    t3:assert_eq(2, M.to_metric(2e-15, "f"))
    t3:assert_eq(2, M.to_metric(2e-18, "a"))
    t3:assert_eq(2, M.to_metric(2e-21, "z"))
    t3:assert_eq(2, M.to_metric(2e-24, "y"))

    t3:assert_eq(2, M.to_metric(2e+1, "da"))
    t3:assert_eq(2, M.to_metric(2e+2, "h"))
    t3:assert_eq(2, M.to_metric(2e+3, "k"))
    t3:assert_eq(2, M.to_metric(2e+6, "M"))
    t3:assert_eq(2, M.to_metric(2e+9, "G"))
    t3:assert_eq(2, M.to_metric(2e+12, "T"))
    t3:assert_eq(2, M.to_metric(2e+15, "P"))
    t3:assert_eq(2, M.to_metric(2e+18, "E"))
    t3:assert_eq(2, M.to_metric(2e+21, "Z"))
    t3:assert_eq(2, M.to_metric(2e+24, "Y"))
  end)
end)

case:describe("metric", function (t2)
  t2:test("can convert to and from all units", function (t3)
    for key, scale in pairs(M.METRIC_UNITS) do
      local v = M.from_metric(1, key)
      t3:assert_eq(scale, v)
      t3:assert_eq(M.to_metric(v, key), 1)
    end
  end)
end)

case:execute()
case:display_stats()
case:maybe_error()
